In [1]:
import pandas as pd

In [2]:
data = pd.read_excel("C:/dataset/Dataset.xlsx")
data.head()

,8,레스토랑명,카테고리,감정/박은지,계절/박창훈,비/정찬영,눈/최인태,기쁨/은지,슬픔/정찬영,분노/주경배,봄/창훈,여름/최인태,가을/원근,겨울/원근
0,더블에스프레소,Back다방,뺵다방커피,음료,없음,없음,없음,음료,음료,없음,없음,없음,없음,없음
1,에스프레소 콤프레또,Back다방,뺵다방커피,음료,없음,없음,없음,음료,음료,없음,없음,없음,없음,없음
2,앗!메리카노(HOT),Back다방,뺵다방커피,음료,없음,없음,없음,음료,음료,없음,없음,없음,없음,없음
3,앗!메리카노(ICED),Back다방,뺵다방커피,음료,없음,없음,없음,음료,음료,없음,없음,없음,없음,없음
4,원조커피(HOT),Back다방,뺵다방커피,음료,없음,없음,없음,음료,음료,없음,없음,없음,없음,없음

### 기쁨 9가지 경우의 수 컬럼 만들기(원근)

In [6]:
data["happy_point"] = 0

for i in range(len(data["기쁨/은지"])):
    if data.iloc[i,7]=="음료" :
        data.iloc[i,14] = 0.2
    elif data.iloc[i,7]=="아이스크림" :
        data.iloc[i,14] = 0.9
    elif data.iloc[i,7]=="없음" :
        data.iloc[i,14] = 0
    elif data.iloc[i,7]=="피자, 스파게티" :
        data.iloc[i,14] = 1
    elif data.iloc[i,7]=="찌개 및 백반/분식" :
        data.iloc[i,14] = 0.1
    elif data.iloc[i,7]=="치킨" :
        data.iloc[i,14] ==0.3
    elif data.iloc[i,7]=="구이류" :
        data.iloc[i,14] = 0.7

In [7]:
data.head()

,8,레스토랑명,카테고리,감정/박은지,계절/박창훈,비/정찬영,눈/최인태,기쁨/은지,슬픔/정찬영,분노/주경배,봄/창훈,여름/최인태,가을/원근,겨울/원근,happy_point
0,더블에스프레소,Back다방,뺵다방커피,음료,없음,없음,없음,음료,음료,없음,없음,없음,없음,없음,0.2
1,에스프레소 콤프레또,Back다방,뺵다방커피,음료,없음,없음,없음,음료,음료,없음,없음,없음,없음,없음,0.2
2,앗!메리카노(HOT),Back다방,뺵다방커피,음료,없음,없음,없음,음료,음료,없음,없음,없음,없음,없음,0.2
3,앗!메리카노(ICED),Back다방,뺵다방커피,음료,없음,없음,없음,음료,음료,없음,없음,없음,없음,없음,0.2
4,원조커피(HOT),Back다방,뺵다방커피,음료,없음,없음,없음,음료,음료,없음,없음,없음,없음,없음,0.2

In [8]:
data["spring_point"] = 0

for i in range(len(data["봄/창훈"])):
    if data.iloc[i,10]=="없음" :
        data.iloc[i,15] = 0
    elif data.iloc[i,10]=="지중해음식" :
        data.iloc[i,15] = 0.6
    elif data.iloc[i,10]=="한정식" :
        data.iloc[i,15] = 1
    elif data.iloc[i,10]=="돼지갈비/갈매기살" :
        data.iloc[i,15] = 0.1
    elif data.iloc[i,10]=="철판구이/볶음밥" :
        data.iloc[i,15] = 0.9
    elif data.iloc[i,10]=="불고기/갈비살/차돌박이" :
        data.iloc[i,15] = 0.4

In [9]:
data["summer_point"] = 0

for i in range(len(data["여름/최인태"])):
    if data.iloc[i,11]=="없음" :
        data.iloc[i,16] = 0
    elif data.iloc[i,11]=="아이스크림" :
        data.iloc[i,16] = 0.7
    elif data.iloc[i,11]=="포장마차" :
        data.iloc[i,16] = 0.1
    elif data.iloc[i,11]=="카레" :
        data.iloc[i,16] = 0.1
    elif data.iloc[i,11]=="치킨" :
        data.iloc[i,16] = 0.3
    elif data.iloc[i,11]=="오리훈제/구이/로스/탕" :
        data.iloc[i,16] = 0.2
    elif data.iloc[i,11]=="냉면" :
        data.iloc[i,16] = 0.8
    elif data.iloc[i,11]=="삼계탕/백숙/찜닭" :
        data.iloc[i,16] = 0.9
    elif data.iloc[i,11]=="업음" :
        data.iloc[i,16] = 0

In [10]:
data["겨울/원근"].unique()

array(['없음', '스테이크하우스', '동남아음식', '씨푸드'], dtype=object)

In [11]:
data["fall_point"] = 0

for i in range(len(data["가을/원근"])):
    if data.iloc[i,12]=="없음" :
        data.iloc[i,17] = 0
    elif data.iloc[i,12]=="브런치" :
        data.iloc[i,17] = 0.8
    elif data.iloc[i,12]=="전라도음식" :
        data.iloc[i,17] = 0.9
    elif data.iloc[i,12]=="동남아음식" :
        data.iloc[i,17] = 0.3
    elif data.iloc[i,12]=="태국음식" :
        data.iloc[i,17] = 0.1
    elif data.iloc[i,12]=="설렁탕/곰탕/도가니탕" :
        data.iloc[i,17] = 0.5

In [12]:
data["winter_point"] = 0

for i in range(len(data["겨울/원근"])):
    if data.iloc[i,13]=="없음" :
        data.iloc[i,18] = 0
    elif data.iloc[i,13]=="스테이크하우스" :
        data.iloc[i,18] = 0.1
    elif data.iloc[i,13]=="동남아음식" :
        data.iloc[i,18] = 0.3
    elif data.iloc[i,13]=="씨푸드" :
        data.iloc[i,18] = 0.4

In [13]:
data["rain_point"] = 0

for i in range(len(data["비/정찬영"])):
    if data.iloc[i,5]=="없음" :
        data.iloc[i,19] = 0
    elif data.iloc[i,5]=="아이스크림" :
        data.iloc[i,19] = -0.6
    elif data.iloc[i,5]=="지중해음식" :
        data.iloc[i,19] = -0.9
    elif data.iloc[i,5]=="남미음식" :
        data.iloc[i,19] = -0.7
    elif data.iloc[i,5]=="철판구이/볶음밥" :
        data.iloc[i,19] = 0.7
    elif data.iloc[i,5]=="중국음식" :
        data.iloc[i,19] = 0.6
    elif data.iloc[i,5]=="삼계탕/백숙/찜닭" :
        data.iloc[i,19] = 0.8
    elif data.iloc[i,5]=="냉면" :
        data.iloc[i,19] = -0.3
    elif data.iloc[i,5]=="쌀국수" :
        data.iloc[i,19] = 0.2
    elif data.iloc[i,5]=="카레" :
        data.iloc[i,19] = -0.1
    elif data.iloc[i,5]=="비빔밥/돌솥밥/쌈밥" :
        data.iloc[i,19] = -0.4
    elif data.iloc[i,5]=="파전/모듬전/빈대떡" :
        data.iloc[i,19] = 0.9
    elif data.iloc[i,5]=="곱창/양/대창/막창" :
        data.iloc[i,19] = 0.4
    elif data.iloc[i,5]=="족발/보쌈" :
        data.iloc[i,19] = 0.2
    elif data.iloc[i,5]=="햄버거" :
        data.iloc[i,19] = 0.8

In [14]:
data["snow_point"] = 0

for i in range(len(data["눈/최인태"])):
    if data.iloc[i,6]=="없음" :
        data.iloc[i,20] = 0
    elif data.iloc[i,6]=="아이스크림" :
        data.iloc[i,20] = -0.5
    elif data.iloc[i,6]=="지중해음식" :
        data.iloc[i,20] = 0.2
    elif data.iloc[i,6]=="한정식" :
        data.iloc[i,20] = -0.2
    elif data.iloc[i,6]=="퓨전레스토랑" :
        data.iloc[i,20] = -0.6
    elif data.iloc[i,6]=="카레" :
        data.iloc[i,20] = -0.4
    elif data.iloc[i,6]=="설렁탕/곰탕/도가니탕" :
        data.iloc[i,20] = 0.7
    elif data.iloc[i,6]=="냉면" :
        data.iloc[i,20] = -0.7
    elif data.iloc[i,6]=="떡" :
        data.iloc[i,20] = -1
    elif data.iloc[i,6]=="퓨전레스트랑" :
        data.iloc[i,20] = -0.6
    elif data.iloc[i,6]=="삼겹살/목살" :
        data.iloc[i,20] = 1
    elif data.iloc[i,6]=="곱창/양/대창/막창" :
        data.iloc[i,20] = -0.1

In [15]:
data["happy_spring_rain"] = data["happy_point"] + data["spring_point"]*0.5 + data["rain_point"]*0.5
data["happy_spring"] = data["happy_point"] + data["spring_point"]*0.5
data["happy_summer_rain"] = data["happy_point"] + data["summer_point"]*0.5 + data["rain_point"]*0.5
data["happy_summer"] = data["happy_point"] + data["summer_point"]*0.5
data["happy_fall_rain"] = data["happy_point"] + data["fall_point"]*0.5 + data["rain_point"]*0.5
data["happy_fall"] = data["happy_point"] + data["fall_point"]*0.5
data["happy_winter_rain"] = data["happy_point"] + data["winter_point"]*0.5 + data["rain_point"]*0.5
data["happy_winter_snow"] = data["happy_point"] + data["winter_point"]*0.5 + data["snow_point"]*0.5
data["happy_winter"] = data["happy_point"] + data["winter_point"]*0.5

In [16]:
happy_score = data.iloc[:,[0,1,-1,-2,-3,-4,-5,-6,-7,-8,-9]]

In [18]:
happy_score

,8,레스토랑명,happy_winter,happy_winter_snow,happy_winter_rain,happy_fall,happy_fall_rain,happy_summer,happy_summer_rain,happy_spring,happy_spring_rain
0,더블에스프레소,Back다방,0.2,0.20,0.20,0.20,0.20,0.20,0.20,0.2,0.20
1,에스프레소 콤프레또,Back다방,0.2,0.20,0.20,0.20,0.20,0.20,0.20,0.2,0.20
2,앗!메리카노(HOT),Back다방,0.2,0.20,0.20,0.20,0.20,0.20,0.20,0.2,0.20
3,앗!메리카노(ICED),Back다방,0.2,0.20,0.20,0.20,0.20,0.20,0.20,0.2,0.20
4,원조커피(HOT),Back다방,0.2,0.20,0.20,0.20,0.20,0.20,0.20,0.2,0.20
...,...,...,...,...,...,...,...,...,...,...,...
342,차돌된장찌개,본가,0.1,0.00,0.50,0.55,0.95,0.15,0.55,0.6,1.00
343,갈비탕,본가,0.1,0.00,0.50,0.55,0.95,0.20,0.60,0.6,1.00
344,본가비빔밥,본가,0.1,0.00,-0.10,0.55,0.35,0.10,-0.10,0.6,0.40
345,본가냉면,본가,0.1,-0.25,-0.05,0.55,0.40,0.50,0.35,0.6,0.45
346,비빔냉면,본가,0.1,-0.25,-0.05,0.55,0.40,0.50,0.35,0.6,0.45

### 창훈님 파일 불러와서 합치기

In [27]:
sad_score = pd.read_csv("C:/dataset/sad_score.csv")
sad_score.rename(columns = {"sad_spring_rainx":"sad_spring","sad_summer_rainx":"sad_summer","sad_fall_rainx":"sad_fall","sad_winter_rainx":"sad_winter"},inplace = True)

In [28]:
sad_score.head()

,sad_spring_rain,sad_spring,sad_summer_rain,sad_summer,sad_fall_rain,sad_fall,sad_winter_rain,sad_winter,sad_winter_snow,sad_winter_snowx
0,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9
1,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9
2,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9
3,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9
4,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9

In [29]:
sad_score.drop(columns = ["sad_winter_snowx"],inplace = True)

In [30]:
sad_score

,sad_spring_rain,sad_spring,sad_summer_rain,sad_summer,sad_fall_rain,sad_fall,sad_winter_rain,sad_winter,sad_winter_snow
0,0.90,0.9,0.90,0.90,0.90,0.90,0.90,0.9,0.90
1,0.90,0.9,0.90,0.90,0.90,0.90,0.90,0.9,0.90
2,0.90,0.9,0.90,0.90,0.90,0.90,0.90,0.9,0.90
3,0.90,0.9,0.90,0.90,0.90,0.90,0.90,0.9,0.90
4,0.90,0.9,0.90,0.90,0.90,0.90,0.90,0.9,0.90
...,...,...,...,...,...,...,...,...,...
342,1.60,1.2,1.15,0.75,1.55,1.15,1.10,0.7,1.10
343,1.60,1.2,1.20,0.80,1.55,1.15,1.10,0.7,1.10
344,0.40,0.6,-0.10,0.10,0.35,0.55,-0.10,0.1,-0.10
345,0.95,1.1,0.85,1.00,0.90,1.05,0.45,0.6,0.45
346,0.95,1.1,0.85,1.00,0.90,1.05,0.45,0.6,0.45

In [31]:
sad_score.columns

Index(['sad_spring_rain', 'sad_spring', 'sad_summer_rain', 'sad_summer',
       'sad_fall_rain', 'sad_fall', 'sad_winter_rain', 'sad_winter',
       'sad_winter_snow'],
      dtype='object')

In [32]:
data_merge = pd.concat([happy_score,sad_score],axis = 1,ignore_index = True)
data_merge.columns = ['menu','restaurant',      'happy_winter',
       'happy_winter_snow', 'happy_winter_rain',        'happy_fall',
         'happy_fall_rain',      'happy_summer', 'happy_summer_rain',
            'happy_spring', 'happy_spring_rain','sad_spring_rain', 'sad_spring', 'sad_summer_rain', 'sad_summer',
       'sad_fall_rain', 'sad_fall', 'sad_winter_rain', 'sad_winter',
       'sad_winter_snow']

### 기쁨, 슬픔 합친거 (원근, 창훈 데이터셋 합친거)

In [33]:
data_merge

,menu,restaurant,happy_winter,happy_winter_snow,happy_winter_rain,happy_fall,happy_fall_rain,happy_summer,happy_summer_rain,happy_spring,happy_spring_rain,sad_spring_rain,sad_spring,sad_summer_rain,sad_summer,sad_fall_rain,sad_fall,sad_winter_rain,sad_winter,sad_winter_snow
0,더블에스프레소,Back다방,0.2,0.20,0.20,0.20,0.20,0.20,0.20,0.2,0.20,0.90,0.9,0.90,0.90,0.90,0.90,0.90,0.9,0.90
1,에스프레소 콤프레또,Back다방,0.2,0.20,0.20,0.20,0.20,0.20,0.20,0.2,0.20,0.90,0.9,0.90,0.90,0.90,0.90,0.90,0.9,0.90
2,앗!메리카노(HOT),Back다방,0.2,0.20,0.20,0.20,0.20,0.20,0.20,0.2,0.20,0.90,0.9,0.90,0.90,0.90,0.90,0.90,0.9,0.90
3,앗!메리카노(ICED),Back다방,0.2,0.20,0.20,0.20,0.20,0.20,0.20,0.2,0.20,0.90,0.9,0.90,0.90,0.90,0.90,0.90,0.9,0.90
4,원조커피(HOT),Back다방,0.2,0.20,0.20,0.20,0.20,0.20,0.20,0.2,0.20,0.90,0.9,0.90,0.90,0.90,0.90,0.90,0.9,0.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,차돌된장찌개,본가,0.1,0.00,0.50,0.55,0.95,0.15,0.55,0.6,1.00,1.60,1.2,1.15,0.75,1.55,1.15,1.10,0.7,1.10
343,갈비탕,본가,0.1,0.00,0.50,0.55,0.95,0.20,0.60,0.6,1.00,1.60,1.2,1.20,0.80,1.55,1.15,1.10,0.7,1.10
344,본가비빔밥,본가,0.1,0.00,-0.10,0.55,0.35,0.10,-0.10,0.6,0.40,0.40,0.6,-0.10,0.10,0.35,0.55,-0.10,0.1,-0.10
345,본가냉면,본가,0.1,-0.25,-0.05,0.55,0.40,0.50,0.35,0.6,0.45,0.95,1.1,0.85,1.00,0.90,1.05,0.45,0.6,0.45
346,비빔냉면,본가,0.1,-0.25,-0.05,0.55,0.40,0.50,0.35,0.6,0.45,0.95,1.1,0.85,1.00,0.90,1.05,0.45,0.6,0.45

### 화남 감정 9가지 경우의 수 컬럼 만들기 (인태님 부분)

In [34]:
data = pd.read_excel("C:/dataset/Dataset.xlsx")
data.head()

,8,레스토랑명,카테고리,감정/박은지,계절/박창훈,비/정찬영,눈/최인태,기쁨/은지,슬픔/정찬영,분노/주경배,봄/창훈,여름/최인태,가을/원근,겨울/원근
0,더블에스프레소,Back다방,뺵다방커피,음료,없음,없음,없음,음료,음료,없음,없음,없음,없음,없음
1,에스프레소 콤프레또,Back다방,뺵다방커피,음료,없음,없음,없음,음료,음료,없음,없음,없음,없음,없음
2,앗!메리카노(HOT),Back다방,뺵다방커피,음료,없음,없음,없음,음료,음료,없음,없음,없음,없음,없음
3,앗!메리카노(ICED),Back다방,뺵다방커피,음료,없음,없음,없음,음료,음료,없음,없음,없음,없음,없음
4,원조커피(HOT),Back다방,뺵다방커피,음료,없음,없음,없음,음료,음료,없음,없음,없음,없음,없음

In [35]:
data["분노/주경배"].unique()

array(['없음', '아이스크림', '초콜릿', '찜 및 볶음류', '찌개 및 백반', '분식', '치킨', '매운 음식',
       '매운음식', '비빔밥'], dtype=object)

In [36]:
data["angry_point"] = 0

for i in range(len(data["분노/주경배"])):
    if data.iloc[i,9]=="없음" :
        data.iloc[i,14] = 0
    elif data.iloc[i,9]=="아이스크림" :
        data.iloc[i,14] = 0.2
    elif data.iloc[i,9]=="초콜릿" :
        data.iloc[i,14] = 0.5
    elif data.iloc[i,9]=="찜 및 볶음류" :
        data.iloc[i,14] = 0.7
    elif data.iloc[i,9]=="찌개 및 백반" :
        data.iloc[i,14] = 0.3
    elif data.iloc[i,9]=="분식" :
        data.iloc[i,14] ==0.8
    elif data.iloc[i,9]=="치킨" :
        data.iloc[i,14] = 0.1
    elif data.iloc[i,9]=="매운 음식" :
        data.iloc[i,14] = 0.9
    elif data.iloc[i,9]=="매운음식" :
        data.iloc[i,14] = 0.9
    elif data.iloc[i,9]=="비빔밥" :
        data.iloc[i,14] = 0.4

In [37]:
data["spring_point"] = 0

for i in range(len(data["봄/창훈"])):
    if data.iloc[i,10]=="없음" :
        data.iloc[i,15] = 0
    elif data.iloc[i,10]=="지중해음식" :
        data.iloc[i,15] = 0.6
    elif data.iloc[i,10]=="한정식" :
        data.iloc[i,15] = 1
    elif data.iloc[i,10]=="돼지갈비/갈매기살" :
        data.iloc[i,15] = 0.1
    elif data.iloc[i,10]=="철판구이/볶음밥" :
        data.iloc[i,15] = 0.9
    elif data.iloc[i,10]=="불고기/갈비살/차돌박이" :
        data.iloc[i,15] = 0.4

In [38]:
data["summer_point"] = 0

for i in range(len(data["여름/최인태"])):
    if data.iloc[i,11]=="없음" :
        data.iloc[i,16] = 0
    elif data.iloc[i,11]=="아이스크림" :
        data.iloc[i,16] = 0.7
    elif data.iloc[i,11]=="포장마차" :
        data.iloc[i,16] = 0.1
    elif data.iloc[i,11]=="카레" :
        data.iloc[i,16] = 0.1
    elif data.iloc[i,11]=="치킨" :
        data.iloc[i,16] = 0.3
    elif data.iloc[i,11]=="오리훈제/구이/로스/탕" :
        data.iloc[i,16] = 0.2
    elif data.iloc[i,11]=="냉면" :
        data.iloc[i,16] = 0.8
    elif data.iloc[i,11]=="삼계탕/백숙/찜닭" :
        data.iloc[i,16] = 0.9
    elif data.iloc[i,11]=="업음" :
        data.iloc[i,16] = 0

In [39]:
data["fall_point"] = 0

for i in range(len(data["가을/원근"])):
    if data.iloc[i,12]=="없음" :
        data.iloc[i,17] = 0
    elif data.iloc[i,12]=="브런치" :
        data.iloc[i,17] = 0.8
    elif data.iloc[i,12]=="전라도음식" :
        data.iloc[i,17] = 0.9
    elif data.iloc[i,12]=="동남아음식" :
        data.iloc[i,17] = 0.3
    elif data.iloc[i,12]=="태국음식" :
        data.iloc[i,17] = 0.1
    elif data.iloc[i,12]=="설렁탕/곰탕/도가니탕" :
        data.iloc[i,17] = 0.5

In [40]:
data["winter_point"] = 0

for i in range(len(data["겨울/원근"])):
    if data.iloc[i,13]=="없음" :
        data.iloc[i,18] = 0
    elif data.iloc[i,13]=="스테이크하우스" :
        data.iloc[i,18] = 0.1
    elif data.iloc[i,13]=="동남아음식" :
        data.iloc[i,18] = 0.3
    elif data.iloc[i,13]=="씨푸드" :
        data.iloc[i,18] = 0.4

In [41]:
data["rain_point"] = 0

for i in range(len(data["비/정찬영"])):
    if data.iloc[i,5]=="없음" :
        data.iloc[i,19] = 0
    elif data.iloc[i,5]=="아이스크림" :
        data.iloc[i,19] = -0.6
    elif data.iloc[i,5]=="지중해음식" :
        data.iloc[i,19] = -0.9
    elif data.iloc[i,5]=="남미음식" :
        data.iloc[i,19] = -0.7
    elif data.iloc[i,5]=="철판구이/볶음밥" :
        data.iloc[i,19] = 0.7
    elif data.iloc[i,5]=="중국음식" :
        data.iloc[i,19] = 0.6
    elif data.iloc[i,5]=="삼계탕/백숙/찜닭" :
        data.iloc[i,19] = 0.8
    elif data.iloc[i,5]=="냉면" :
        data.iloc[i,19] = -0.3
    elif data.iloc[i,5]=="쌀국수" :
        data.iloc[i,19] = 0.2
    elif data.iloc[i,5]=="카레" :
        data.iloc[i,19] = -0.1
    elif data.iloc[i,5]=="비빔밥/돌솥밥/쌈밥" :
        data.iloc[i,19] = -0.4
    elif data.iloc[i,5]=="파전/모듬전/빈대떡" :
        data.iloc[i,19] = 0.9
    elif data.iloc[i,5]=="곱창/양/대창/막창" :
        data.iloc[i,19] = 0.4
    elif data.iloc[i,5]=="족발/보쌈" :
        data.iloc[i,19] = 0.2
    elif data.iloc[i,5]=="햄버거" :
        data.iloc[i,19] = 0.8

In [42]:
data["snow_point"] = 0

for i in range(len(data["눈/최인태"])):
    if data.iloc[i,6]=="없음" :
        data.iloc[i,20] = 0
    elif data.iloc[i,6]=="아이스크림" :
        data.iloc[i,20] = -0.5
    elif data.iloc[i,6]=="지중해음식" :
        data.iloc[i,20] = 0.2
    elif data.iloc[i,6]=="한정식" :
        data.iloc[i,20] = -0.2
    elif data.iloc[i,6]=="퓨전레스토랑" :
        data.iloc[i,20] = -0.6
    elif data.iloc[i,6]=="카레" :
        data.iloc[i,20] = -0.4
    elif data.iloc[i,6]=="설렁탕/곰탕/도가니탕" :
        data.iloc[i,20] = 0.7
    elif data.iloc[i,6]=="냉면" :
        data.iloc[i,20] = -0.7
    elif data.iloc[i,6]=="떡" :
        data.iloc[i,20] = -1
    elif data.iloc[i,6]=="퓨전레스트랑" :
        data.iloc[i,20] = -0.6
    elif data.iloc[i,6]=="삼겹살/목살" :
        data.iloc[i,20] = 1
    elif data.iloc[i,6]=="곱창/양/대창/막창" :
        data.iloc[i,20] = -0.1

In [46]:
data["angry_spring_rain"] = data["angry_point"] + data["spring_point"]*0.5 + data["rain_point"]*0.5
data["angry_spring"] = data["angry_point"] + data["spring_point"]*0.5
data["angry_summer_rain"] = data["angry_point"] + data["summer_point"]*0.5 + data["rain_point"]*0.5
data["angry_summer"] = data["angry_point"] + data["summer_point"]*0.5
data["angry_fall_rain"] = data["angry_point"] + data["fall_point"]*0.5 + data["rain_point"]*0.5
data["angry_fall"] = data["angry_point"] + data["fall_point"]*0.5
data["angry_winter_rain"] = data["angry_point"] + data["winter_point"]*0.5 + data["rain_point"]*0.5
data["angry_winter_snow"] = data["angry_point"] + data["winter_point"]*0.5 + data["snow_point"]*0.5
data["angry_winter"] = data["angry_point"] + data["winter_point"]*0.5

In [50]:
angry_score = data.iloc[:,[-1,-2,-3,-4,-5,-6,-7,-8,-9]]

In [51]:
angry_score.head()

,angry_winter,angry_winter_snow,angry_winter_rain,angry_fall,angry_fall_rain,angry_summer,angry_summer_rain,angry_spring,angry_spring_rain
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [54]:
menu_score_all = pd.concat([happy_score,sad_score,angry_score],axis = 1,ignore_index = True)
menu_score_all.columns = ['menu','restaurant',      'happy_winter',
       'happy_winter_snow', 'happy_winter_rain',        'happy_fall',
         'happy_fall_rain',      'happy_summer', 'happy_summer_rain',
            'happy_spring', 'happy_spring_rain','sad_spring_rain', 'sad_spring', 'sad_summer_rain', 'sad_summer',
       'sad_fall_rain', 'sad_fall', 'sad_winter_rain', 'sad_winter',
       'sad_winter_snow','angry_winter',
       'angry_winter_snow', 'angry_winter_rain',        'angry_fall',
         'angry_fall_rain',      'angry_summer', 'angry_summer_rain',
            'angry_spring', 'angry_spring_rain']

### 최종 가중치 데이터셋

In [55]:
menu_score_all

,menu,restaurant,happy_winter,happy_winter_snow,happy_winter_rain,happy_fall,happy_fall_rain,happy_summer,happy_summer_rain,happy_spring,...,sad_winter_snow,angry_winter,angry_winter_snow,angry_winter_rain,angry_fall,angry_fall_rain,angry_summer,angry_summer_rain,angry_spring,angry_spring_rain
0,더블에스프레소,Back다방,0.2,0.20,0.20,0.20,0.20,0.20,0.20,0.2,...,0.90,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00
1,에스프레소 콤프레또,Back다방,0.2,0.20,0.20,0.20,0.20,0.20,0.20,0.2,...,0.90,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00
2,앗!메리카노(HOT),Back다방,0.2,0.20,0.20,0.20,0.20,0.20,0.20,0.2,...,0.90,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00
3,앗!메리카노(ICED),Back다방,0.2,0.20,0.20,0.20,0.20,0.20,0.20,0.2,...,0.90,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00
4,원조커피(HOT),Back다방,0.2,0.20,0.20,0.20,0.20,0.20,0.20,0.2,...,0.90,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,차돌된장찌개,본가,0.1,0.00,0.50,0.55,0.95,0.15,0.55,0.6,...,1.10,0.3,0.20,0.70,0.75,1.15,0.35,0.75,0.8,1.20
343,갈비탕,본가,0.1,0.00,0.50,0.55,0.95,0.20,0.60,0.6,...,1.10,0.3,0.20,0.70,0.75,1.15,0.40,0.80,0.8,1.20
344,본가비빔밥,본가,0.1,0.00,-0.10,0.55,0.35,0.10,-0.10,0.6,...,-0.10,0.4,0.30,0.20,0.85,0.65,0.40,0.20,0.9,0.70
345,본가냉면,본가,0.1,-0.25,-0.05,0.55,0.40,0.50,0.35,0.6,...,0.45,0.0,-0.35,-0.15,0.45,0.30,0.40,0.25,0.5,0.35
346,비빔냉면,본가,0.1,-0.25,-0.05,0.55,0.40,0.50,0.35,0.6,...,0.45,0.0,-0.35,-0.15,0.45,0.30,0.40,0.25,0.5,0.35

In [56]:
menu_score_all.to_csv("C:/dataset/menu_score_all.csv", encoding="utf-8-sig", index = False)